### ISSUE TITLE
How to set alias prisma in windows

### ISSUE THREAD

**Issue by tuwibu** [steebchen/prisma-client-go#1085]
I have tried setx, but its not work
```
setx prisma "go run github.com/steebchen/prisma-client-go"
```

**Comment by steebchen** [comment]
Are you using WSL? If not I'd recommend to do so as then you can just use the [alias shortcut](https://goprisma.org/docs/getting-started/cli#shortcut).

**Comment by tuwibu** [comment]
Thanks you ^^
