### ISSUE TITLE
How to get data with relationship

### ISSUE THREAD

**Issue by tuwibu** [steebchen/prisma-client-go#1093]
I want use like this code js, but i dont know how to implement in goprisma
```js
const article = await fastify.prisma.article.findFirst({
  include: {
    Website: true
  }
});
```
```js
const article = await fastify.prisma.article.findFirst({
  select: {
    id: true,
    Website: {
      select: {
        id: true,
        domain: true
      }
    }
  }
});
```
How to get count in table
```js
const article = await fastify.prisma.article.count();
```

**Comment by steebchen** [comment]
Please check the article [Fetching additional data](https://goprisma.org/docs/walkthrough/fetch), I might have to improve the docs regarding that...

Select is currently [not supported](https://github.com/steebchen/prisma-client-go/issues/346)

Count is currently [not supported](https://github.com/steebchen/prisma-client-go/issues/229)

Let me know if this resolves your issue for now, please upvote and/or follow the linked issues if you want to have this feature!
