### ISSUE TITLE
Allow LinkOptional - style FK constraints

### ISSUE THREAD

**Issue by nettrino** [steebchen/prisma-client-go#1142]
It is possible to have a FK constraints that are potentially empty in prisma, similar to the following

```prisma
model Bar {
    id          String    @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
}

model Foo {
    id    String    @id @default(dbgenerated("gen_random_uuid()")) @db.Uuid
    barId String?   @map("bar_id") @db.Uuid
    bar   Bar? @relation(fields: [bar_id], references: [id])
}
```

When emitting `Create` and `Upsert` directives, `Link` operations where an empty string is passed will fail in the attempt to convert to a UUID. As a result, one needs to be creating more complex if/else conditions to account for possibly empty foreign keys. It would be useful to either expose a `LinkOptional` directive or equivalent to allow users to create a single `Create` or `Upsert` statement

**Comment by steebchen** [comment]
The following should work for single foreign keys:

```go
var v *string
created, err := client.Post.FindUnique(
    Post.ID.Equals("a"),
).Update(
    Post.Author.Link(
        User.ID.EqualsIfPresent(v),
    ),
).Exec(ctx)
if err != nil {
    t.Fatalf("fail %s", err)
}
```

**Comment by nettrino** [comment]
This is fine when the record exists already, however it forces a secondary lookup once you want to create a record and optionally link it to multiple tables depending on whether a FK is present, unless I'm misunderstanding the API which is highly likely

**Comment by steebchen** [comment]
Hm can you maybe provide an example code of how you would do it right now and how you would wish to do it? So I can fully understand your use-case.

**Comment by nettrino** [comment]
As discussed offline on discord, it is possible do a CreateOne operation directly and use something like 

```golang
report, err = client.Report.CreateOne(
  db.Report.Workspace.Link(
    db.Workspace.ID.Equals(workspaceId),
  ),
  
  db.Report.Repository.Link(
    db.Repository.ID.EqualsIfPresent(repositoryId),
  ),
...
```

which addresses the constraint

**Comment by steebchen** [comment]
Indeed. I have also created #1146 and #1145 as minor tasks as a follow up on this.
