### ISSUE TITLE
404 with openssl 3.2.x

### ISSUE THREAD

**Issue by javacode123** [steebchen/prisma-client-go#1143]
https://binaries.prisma.sh/all_commits/0ca5ccbcfa6bdc81c003cf549abe4269f59c41e5/debian-openssl-3.2.x/schema-engine.gz
i will 404

**Comment by javacode123** [comment]
cmmit: 694eea289a8462c80264df36757e4fdc129b1b32 also need

**Comment by steebchen** [comment]
Which version of the Go client are you using? Can you please share the configuration part of your prisma.schema? Thanks!

**Comment by javacode123** [comment]
> Which version of the Go client are you using? Can you please share the configuration part of your prisma.schema? Thanks!

i forked you repo, just use it to download prisma engine. and download url is https://binaries.prisma.sh/all_commits/694eea289a8462c80264df36757e4fdc129b1b32/debian-openssl-3.2.x/schema-engine.gz

**Comment by steebchen** [comment]
I'm not sure what you are doing or how you are running into this. Are you manually downloading this file? Or does it occur when you run the Go client?

The available binaries are published by Prisma and can be found here https://www.prisma.io/docs/orm/reference/prisma-schema-reference#binarytargets-options

**Comment by javacode123** [comment]
i forked this repo base on commit: 7e0b3e5294ea041daff0e531486fd1697acfe5d0. Because my go program need download prisma cli, my http iterface need run query-engine. But when i run program in github work space, it get err `could not download engines: could not download https://binaries.prisma.sh/all_commits/694eea289a8462c80264df36757e4fdc129b1b32/debian-openssl-3.2.x/query-engine.gz to /home/gitpod/.cache/fireboom/prisma/694eea289a8462c80264df36757e4fdc129b1b32/prisma-query-engine-debian-openssl-3.2.x: received code 404 from https://binaries.prisma.sh/all_commits/694eea289a8462c80264df36757e4fdc129b1b32/debian-openssl-3.2.x/query-engine.gz: <!DOCTYPE html>\n<html lang=\"en\">\n  <head>\n `

**Comment by steebchen** [comment]
I see so you are getting the error in Gitub workspaces. Are you sure this is the correct commit? It's so old (from 2022)?

**Comment by javacode123** [comment]
> I see so you are getting the error in Gitub workspaces. Are you sure this is the correct commit? It's so old (from 2022)?

yes, i am not sync new code.

**Comment by javacode123** [comment]
i also want to know why need to mush prisma cli with linux platform? why not like macos, ervery arch has ervery prisma cli
https://github.com/steebchen/prisma-client-go/blob/main/binaries/platform/platform.go#L39

**Comment by steebchen** [comment]
Please use the latest version. It uses only one binary per arch and platform.

**Comment by matt852** [comment]
I am seeing this same error.  It is coming from attempting to install Ghostfolio using Docker Compose.  See [this issue](https://github.com/ghostfolio/ghostfolio/issues/1879) for more details.

It sounds like the workaround is to point to a new, updated binary in this repo instead?

**Comment by steebchen** [comment]
@matt852 The latest Go client is not using any of these -ssl binaries, so in a newer version, this can't really happen; unless you are overwriting the binaries using `binaryTargets`. Please open a new issue with your prisma schema, the Go client version, and as much other info as possible.
