### ISSUE TITLE
Error: Redeclared in this block

### ISSUE THREAD

**Issue by saaamxzy** [steebchen/prisma-client-go#1165]
I have checked [Generated code contains redeclared fields](https://github.com/steebchen/prisma-client-go/issues/473), [Error: Redeclared in this block](https://github.com/steebchen/prisma-client-go/issues/152) and [Bug: code generation breaks with relation](https://github.com/steebchen/prisma-client-go/issues/126) but it seems like there is something else that is causing the error in my case:

`prisma/db/db_gen.go:3330:7: promptFieldComments redeclared in this block
        prisma/db/db_gen.go:3284:7: other declaration of promptFieldComments`

and the prisma schema file contains:

`comments                Int                @default(0)`
and 

`Comments              Comment[]`

The generated file looks like:

`const promptFieldComments promptPrismaFields = "comments"`

and 

`const promptFieldComments promptPrismaFields = "Comments"`

So I assume that we are not handling same field names but with different cases. In the case above the letter C is in different cases.

**Comment by steebchen** [comment]
The Go client fails with the same fields with different cases, you would have to use a different name and use `@map()` to map it to the correct field in the database. The above works in the Prisma client but it simply doesn't work with Go as all fields are PascalCase, while in JS fields can be PascalCase or camelCase.
