### ISSUE TITLE
Feedback for “Transactions”: How to manually rollback?

### ISSUE THREAD

**Issue by luatnd** [steebchen/prisma-client-go#1220]
How to rollback if no stuff was updated (no stuff found for update)? 
It would be nice if we have sth like the interactive transaction in PrismaJS version.
```go
postTx := client.Post.Create(…).Tx()
stuffTx := client.Stuff.FindMany(
		...
		db.Stuff.Version.Equals(version), // version is not a part of Primary Key so we cannot use FindUnique
	).Update(
		...sth.here...        
		db.Stuff.Version.Set(version+1),
	).Tx()

tx := client.Transaction(postTx, stuffTx)
err := tx.Exec(ctx)
if err != nil {
  panic("Transaction failed. Database not modified.")
}

post := postTx.Result()
stuff := stuffTx.Result()

if stuff.Count <= 0 {
  // DO ROLLBACK here in case of no stuff was updated
}
```

**Comment by luatnd** [comment]
Found a possible solution here: 
https://github.com/steebchen/prisma-client-go/issues/237#issuecomment-724583143

But for the `db.Tx()`, `Tx()` is not exist in var `db`

**Comment by steebchen** [comment]
Yes this would require [interactive transactions](https://github.com/steebchen/prisma-client-go/issues/569). It's currently not implemented. You would need to think of a way to do this directly using the query. If there is more demand for the feature request I might look into it.
