### ISSUE TITLE
Select undefined (type db.modelFindMany has no field or method Select)

### ISSUE THREAD

**Issue by komarapc** [steebchen/prisma-client-go#1260]
Select is undefined

```go
func GetAllPost() ([]db.PostModel, error) {
	client := db.NewClient()
	posts, _ := client.Post.FindMany().Select(db.Post.Title.Field()).Exec(context.Background())
	return posts, nil
}
```

**Comment by kusaljr** [comment]
Same issue encountered

using versiongithub.com/steebchen/prisma-client-go v0.36.0

**Comment by steebchen** [comment]
@kusaljr can you please share your schema, thank you 🙏

**Comment by kusaljr** [comment]
I'm using the default schema from documentation 

```
datasource db {
    // could be postgresql or mysql
    provider = "sqlite"
    url      = "file:dev.db"
}

generator db {
    provider = "go run github.com/steebchen/prisma-client-go"
}

model Post {
    id        String   @id @default(cuid())
    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt
    title     String
    published Boolean
    desc      String?
}
```

@steebchen

**Comment by steebchen** [comment]
You need to be on [v0.37.0](https://github.com/steebchen/prisma-client-go/releases/tag/v0.37.0)

**Comment by kusaljr** [comment]
@steebchen 
problem using v0.37.0 on same schema

<img width="642" alt="image" src="https://github.com/steebchen/prisma-client-go/assets/51640562/7eff9681-761c-408d-a1e6-f18ca61f7932">

I'm using M2, go version go1.22.3 darwin/arm64

**Comment by steebchen** [comment]
Hmm that's weird, can you please open a new issue? Thanks.
