### ISSUE TITLE
Build Error for new projects or Quickstart repo

### ISSUE THREAD

**Issue by ohthepain** [steebchen/prisma-client-go#1274]
Repro steps (MacOS):

Clone the Quickstart repo: git@github.com:steebchen/prisma-go-demo.git
Run 'go build'
Observed: ERROR: package slices is not in GOROOT (/usr/local/go/src/slices)

The same error occurs when you create a new project.

**Comment by steebchen** [comment]
Please use upgrade go to 1.21, or downgrade to an older version of prisma-client-go.
