### ISSUE TITLE
 Problem on db push operation on v0.37.0 

### ISSUE THREAD

**Issue by kusaljr** [steebchen/prisma-client-go#1278]
<img width="688" alt="image" src="https://github.com/steebchen/prisma-client-go/assets/51640562/0b69bdb0-9034-4a46-918c-9943cdc29dd8">

I'm using M2, go version go1.22.3 darwin/arm64

My schema

```
datasource db {
    // could be postgresql or mysql
    provider = "sqlite"
    url      = "file:dev.db"
}

generator db {
    provider = "go run github.com/steebchen/prisma-client-go"
}

model Post {
    id        String   @id @default(cuid())
    createdAt DateTime @default(now())
    updatedAt DateTime @updatedAt
    title     String
    published Boolean
    desc      String?
}
```

**Comment by steebchen** [comment]
Does `generate` work? I'm guessing the same issue? Really weird, I haven't tested on M2 as I don't have access to one (I'm on M1)

**Comment by kusaljr** [comment]
Same issue in generate also 

<img width="624" alt="image" src="https://github.com/steebchen/prisma-client-go/assets/51640562/ec28690d-5d53-4958-b253-b8d5f8e8000f">

@steebchen

**Comment by kusaljr** [comment]
Any updates on this issue?

**Comment by steebchen** [comment]
If you can set `PRISMA_CLIENT_GO_LOG=debug` and then re-run everything and paste it here, that might be helpful for me to debug

**Comment by kusaljr** [comment]
Here is debug log for generate
<img width="1151" alt="image" src="https://github.com/steebchen/prisma-client-go/assets/51640562/4e220df7-f33b-4463-8f16-17ead847b45b">


Here is debug log for db push
<img width="1161" alt="image" src="https://github.com/steebchen/prisma-client-go/assets/51640562/e79eabe7-2813-4457-b67d-5fef2c03d94e">

**Comment by steebchen** [comment]
Thanks. Can you please try running the engine in your console:

```
/Users/macbook/Library/Caches/prisma/binaries/cli/5.13.0/prisma-cli-darwin-arm64 version
```

and check if it has the same error?
