### ISSUE TITLE
Insensitive case

### ISSUE THREAD

**Issue by qg5** [steebchen/prisma-client-go#1355]
I'm trying to query some data using the `FindMany` method. Currently using postgres.

```go
db.Product.Or(
	db.Product.And(
		db.Product.Name.Contains(searchTerm),
	),
	db.Product.And(
		db.Product.Name.Mode(db.QueryModeInsensitive),
	),
),
```
I have tried without the "Or" and with the "QueryModeDefault"

However, it's still being case sensitive, why is this happening?

**Comment by qg5** [comment]
I figured out the reason it happens, however I can't really come up with a fix since it triggers the duplicate field error

What i want:
```js
where: {
    name: {
      contains: searchTerm,
      mode: 'insensitive',
    },
  },
```

But instead, when executing the query in the previous comment in order to avoid duplicate error I get a completely different query which doesn't return any data

**Comment by steebchen** [comment]
```
db.Product.Or(
	db.Product.And(
		db.Product.Name.Contains(searchTerm),
		db.Product.Name.Mode(db.QueryModeInsensitive),
	),
),
```

can you try this?

**Comment by steebchen** [comment]
Can you send your full query please? I can't reproduce with just and `AND` and a contains + mode. (https://github.com/steebchen/prisma-client-go/pull/1362)

**Comment by qg5** [comment]
This code:

```go
db.Product.Or(
	db.Product.And(
		db.Product.Name.Contains("prisMA"),
	),
	db.Product.And(
		db.Product.Name.Mode(db.QueryModeInsensitive),
	),
),
```

Returns this query:
```js
  where: {
    OR: [
      {
        AND: [
          {
            name: {
              mode: "insensitive",
            },
          },
        ],
      },
      {
        AND: [
          {
            name: {
              contains: "prisMA",
            },
          },
        ],
      },
    ],
  }
```

The query above will return no results and no duplicate error because the `mode` needs to be placed in the same place as the `contains` or `equals` or whatever

And if you look at [postgresql provider](https://www.prisma.io/docs/orm/prisma-client/queries/case-sensitivity#postgresql-provider) you can see the type of query it expects for case sensitivity, which you can get with this code:
```go
db.Product.And(
	db.Product.Name.Contains("prisMA"),
	db.Product.Name.Mode(db.QueryModeInsensitive),
),
```

expected query:
```js
  where: {
    AND: [
      {
        name: {
          mode: "insensitive",
          contains: "prisMA",
        },
      },
    ],
}
```

And of course, to avoid the duplicate code you must add that if statement to the `checkRequired` function

**Comment by qg5** [comment]
> I don't understand.
> 
> ```go
> db.Product.Or(
> 	db.Product.And(
> 		db.Product.Name.Contains("prisMA"),
> 	),
> 	db.Product.And(
> 		db.Product.Name.Mode(db.QueryModeInsensitive),
> 	),
> ),
> ```
> 
> This code is expected to _not_ work, because the mode is in a different object.

Correct

> ```go
> db.Product.And(
> 	db.Product.Name.Contains("prisMA"),
> 	db.Product.Name.Mode(db.QueryModeInsensitive),
> ),
> ```
> 
> This code _is_ expected work, is this not working for you?

Yes, that code will work and obtain the result, however it will return an error (duplicate field) along the result which messes with the whole flow, the only way is modifying the `checkFields` function to avoid getting that error. Sorry if my explanations are bad

**Comment by qg5** [comment]
I finally fixed it

It's unknown to me why it happened but in my code, I would execute 2 queries in the same function, one which would get the total amount of results without pagination, that way I can know the total amount of pages, and then I would get the products for the given page

```go
where := []db.ProductWhereParam{
		db.Product.And(
			db.Product.Name.Contains(searchTerm),
			db.Product.Name.Mode(db.QueryModeInsensitive),
		),
}
query := r.client.Product.FindMany(where...)

totalProductModels, err := query.Exec(context.Background())
if err != nil { ... }

productModels, err := query.Skip(count).Take(pageSize).Exec(context.Background())
if err != nil { ... } // duplicate error would happen here
```

So, this code ended up fixing it, I basically create another FindMany query only to get the total products, which I don't quite like but it's the only way I can get it working without having to modify the `checkFields` function

```go
query2 := r.client.Product.FindMany(where...)
totalProductModels, err := query2.Exec(context.Background())
if err != nil { ... }
```

Could you explain why it happens?

**Comment by steebchen** [comment]
Thanks for the additional info, thanks. It's indeed quite weird, I'm not sure why this happens

**Comment by qg5** [comment]
I figured it happens somewhere in `buildFields` inside the first loop, so I decided to rewrite it, apparently it was messing up with `f.Fields` and values from past queries would be kept in it which would trigger the duplicate error if you tried to execute that same query

With the old `buildFields`, an error would be triggered in the second query with this code:
```go
where := []db.ProductWhereParam{
  db.Product.Name.Contains("prisMA"),
  db.Product.Name.Mode(db.QueryModeInsensitive),
}

query := r.client.Product.FindMany(where...)
_, err := query.Exec(context.Background())
if err != nil {
  log.Println("#q1 err:", err)
}

_, err = query.Exec(context.Background())
if err != nil {
  log.Println("#q2 err:", err)
}
```

This is what I changed it to (it still keeps the nature of checking for duplicates effectively, just no pointers this time):
```go
var final []Field
// remember the order in which the unique fields where added to the map
var uniqueNames []string

// check for duplicate fields so that multiple queries on the same field will be shared
// this is necessary for json filters and more
uniqueFields := make(map[string]Field)
for _, f := range fields {
if existingField, ok := uniqueFields[f.Name]; ok {
	// Check if field is a model operation
	if f.Fields != nil && f.Name != "AND" && f.Name != "OR" && f.Name != "NOT" {
		// Join sub-fields
		existingField.Fields = append(existingField.Fields, f.Fields...)
		uniqueFields[f.Name] = existingField
	} else {
		// Add the field directly if it's a list or contains a value
		final = append(final, f)
	}
} else {
	uniqueFields[f.Name] = f
	uniqueNames = append(uniqueNames, f.Name)
}
}

// use the list of unique names to add the unique fields in a deterministic order
for _, name := range uniqueNames {
final = append(final, uniqueFields[name])
}
```

**Comment by steebchen** [comment]
@qg5 I haven't had the chance to look into it more closely, is it still an issue? If it's a bug it should be still fixed and issue would be better kept open.
