### ISSUE TITLE
Best Practices for Connection Management and Pooling in prisma-client-go with MySQL

### ISSUE THREAD

**Issue by Fate0x01** [steebchen/prisma-client-go#1403]
Hi! I’m using prisma-client-go with MySQL, and I’d like to know the recommended best practices for connection management.

1. Should I maintain a single global Prisma client instance across my application, or is it better to create a new client instance each time I need to interact with the database, explicitly closing it afterward?

2. Is there a built-in way to use connection pooling in prisma-client-go when working with MySQL, or is there a recommended approach to manage connection pools effectively?

Thanks in advance for the guidance!

**Comment by steebchen** [comment]
Hi, yes, a single prisma client is required, do not create a client per action.
The recommended approach is to use a connection pooler like pgbouncer and following the connection pool docs here https://www.prisma.io/docs/orm/prisma-client/setup-and-configuration/databases-connections/connection-pool. Let me know if you have any other questions, closing this for now but feel free to re-open or join the community https://goprisma.org/docs/community.
