### ISSUE TITLE
Provide proper error handling for unique constraints

### ISSUE THREAD

**Issue by steebchen** [steebchen/prisma-client-go#213]
Apart from ErrNotFound, there are currently no other exported errors. We should export various errors such as unique constraint violations and so on. They should also contain details if possible.

For example, checking for a unique constraint violation could look as follows:

```go
user, err := db.User.CreateOne(...)
if v, ok := prisma.IsUniqueConstraintViolation(err); ok {
  // do something here
  log.Printf("duplicate entry on columns %s", v.Fields)
} else if err != nil {
 // probably nothing we can do here
  return err
}
```

**Comment by darmie** [comment]
I am having similar problem and it's confusing...

This was working before:
```graphql
mutation {
  addBranch(restaurantId: 14, data:{
    name:"Amuwo Branch",
    contactEmail:"dami@bukka.com",
    contactPhone:"09024472756",
    location: {
      city: "Lagos",
      state:"Lagos",
      landmark:"Big Mosque",
      street: "Apple Junction",
      lga:"Amuwo Odofin",
      lat: 6.471063,
      lng: 3.312688
    }
  }){
    id
  }
}
```

Now I get this:
```json
{
  "errors": [
    {
      "message": "cannot find restaurant of ID 14 : ErrNotFound",
      "path": [
        "addBranch"
      ]
    }
  ],
  "data": null
}
```

**Comment by steebchen** [comment]
@darmie Can you please open a new issue? Thanks!

**Comment by darmie** [comment]
@steebchen nevermind, it works now.. It seems the server that handles the DB transactions was not ready.

**Comment by steebchen** [comment]
Returning detailed errors such as:

```go
type UniqueConstraintViolation struct {
	Message string
	Fields []string
}

type (e UniqueConstraintViolation) Error() string {
	return e.Message
}
```

is unfortunately not as simple as it sounds, since different databases return different information.

For example, a unique constraint violation error in Postgres returns the fields, while MySQL returns the violated index name.

We could introduce errors depending on database provider, such as `PostgresUniqueConstraintViolation` and so on to solve this problem.

**Comment by steebchen** [comment]
depends on https://github.com/prisma/prisma/issues/5040

**Comment by steebchen** [comment]
Implementation via #1069. Please comment on the PR for any feedback. For other kinds of errors, please open a new issue.
