### ISSUE TITLE
Automate Prisma CLI binary publish process

### ISSUE THREAD

**Issue by steebchen** [steebchen/prisma-client-go#298]
to do:
- [x] Make darwin arm64 binaries work

**Comment by hi019** [comment]
[goreleaser](https://github.com/goreleaser/goreleaser) is great for this! I'm setting it up for our CLI, let me know if I can help.

**Comment by steebchen** [comment]
This is really just for the Prisma CLI which is packed into the Go client – so unfortunately not related to Go. This issue probably belongs somewhere else 😅
