### ISSUE TITLE
Select only requested fields

### ISSUE THREAD

**Issue by araufdogan** [steebchen/prisma-client-go#346]
Hello,

I'm trying to build a GraphQL service using gqlgen and prisma2. I want to select only requested fields from prisma using gqlgen [field collection](https://gqlgen.com/reference/field-collection/), is it possible? Does prisma golang client supports [field selection](https://www.prisma.io/docs/concepts/components/prisma-client/field-selection)?

**Comment by steebchen** [comment]
Unfortunately, it's not supported yet. We want to have the feature at some point but don't have the capacity for it in the near future.

**Comment by steebchen** [comment]
Syntax proposal:

```go
users, err := client.User.FindMany().Select("id", "email", "username").Exec(ctx)
```

The `users` variable would still be of type `[]db.UserModel`, but the connection would only fetch the selected fields, and unselected fields would be nil or the Go default value.

**Comment by Pwnoz0r** [comment]
Any updates / community accepted way to do this?

**Comment by steebchen** [comment]
No, and we don't expect to have this feature anytime soon due to constrained resources

**Comment by fragdance1** [comment]
Don't know if this still is requested, but just got to playing around with prisma go (after prisma ts), and got it to work somehow:

```
	var folder db.MediaFolderModel
	query := global.DB.MediaFolder.FindUnique(db.MediaFolder.Name.Equals("cache")).ExtractQuery()

	query.Outputs = []builder.Output{{Name: "id"}, {Name: "name"}}
	err := query.Exec(context.Background(), &folder)
```
Returns the following:

{```

	"id": 5,
	"name": "cache",
	"path": "",
	"type": ""
}
```

i.e. path and type is not fetched (actually not in json from prisma engine), but set as empty strings because of golang struct

**Comment by steebchen** [comment]
Oh wow, that is pretty cool @fragdance1. If you want to create a PR to add a method `.Select([]string{})` to the query builder to select these fields, I'd be happy to review and merge it!

I think the question left for this issue specifically would be if passing the args directly from gqlgen would work.

**Comment by fragdance1** [comment]
Actually forked it to https://github.com/fragdance1/prisma-client-go in order to implement just that (and not mess anything up), and now I can call it like:

`episodes, err := global.DB.Episode.FindMany(db.Episode.ShowID.Equals(id)).
		Select([]string{"name", "id", "episodeNumber", "seasonNumber", "progress", "owned"}).
		With(db.Episode.VideoFiles.Fetch().
			Select([]string{"id", "extension"}).
			With(db.VideoFile.Subtitles.Fetch())).
		Exec(context.Background())`

I've also added a replacement function ExecJson that returns the raw json from the call, thus excluding the fields not retrieved. Feel free to check it out/grab the code

**Comment by steebchen** [comment]
@fragdance1 I think this would be awesome to have in the client. I'd be happy to review and merge a PR for this!

**Comment by fragdance1** [comment]
@steebchen Just tried to push to a new branch feat/prisma-select-statement, but got access denied.

 Anyways, the code in my branch turns this:
![bild](https://user-images.githubusercontent.com/24291430/177198914-6e292cc0-14ef-4c03-85a6-bb45e4b8d175.png)

to this:
![bild](https://user-images.githubusercontent.com/24291430/177198971-f47c1ca2-09ce-42f7-b8f2-efa07284a0c6.png)

When using the code:
![bild](https://user-images.githubusercontent.com/24291430/177199021-1d27822f-ea79-401f-ba41-836ef62868be.png)

As can be seen in the screenshots it works on multiple levels (here the credit goes to you), and I have select on both the Episode model and the relational Videofile model

**Comment by steebchen** [comment]
@fragdance1 You can just push it to your repo and then create a PR from your branch to this repo

**Comment by Blyxyas** [comment]
@fragdance1 May you create a PR with your change, please?

**Comment by fragdance1** [comment]
Hi,

sorry about the delay, got sidetracked at work.

Problem is that I pushed a lot of changes, so no single 'Select'-branch.
Think the easiest is for you to make the changes (there aren't that many).

In generator/templates/actions/find.gotpl add

func (r {{ $result }}) Select(params []string) {{ $result }} {
  r.query.Outputs = []builder.Output{}
  for _, q := range params {
    r.query.Outputs = append(r.query.Outputs,builder.Output{
      Name:    q,
    })
  }
  return r
}

And that's it
