### ISSUE TITLE
set datasource url programmatically

### ISSUE THREAD

**Issue by araufdogan** [steebchen/prisma-client-go#347]
Hello,

I have my own config file and I want to set datasource url programmatically in prisma file. How can I do this?

**Comment by steebchen** [comment]
It's not possible right now. I have already raised this internally.

In the meanwhile, you can declare an environment variable in the schema file and provide that directly or use `os.Setenv`:

```schema
datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}
```

**Comment by steebchen** [comment]
You can now override the data source URL, see #1060
