### ISSUE TITLE
Error in build docker image with prisma and go

### ISSUE THREAD

**Issue by nurrohim11** [steebchen/prisma-client-go#746]
Hi everyone.
I am using prisma in golang and i have issue prisma/db is not in GOROOT.
issue is showing on build docker image in gitlab.

look the image bottom for the detail issue
![image](https://user-images.githubusercontent.com/30541324/171087850-21a9f756-2736-400e-8f2d-de7c09b098fb.png)

**Comment by steebchen** [comment]
Please share some more info, like your full dockerfile.
