### ISSUE TITLE
failed fetching binaries: could not download [BINARY_URL]

### ISSUE THREAD

**Issue by CompeyDev** [steebchen/prisma-client-go#883]
Running a simple `prisma generate` seems to fail as the CLI cannot download from a [binaries.prisma.sh](https://binaries.prisma.sh) build as the Cloudflare R2 instance returns a 404 with an HTML response for the URL.

![error output](https://github.com/steebchen/prisma-client-go/assets/74418041/06796812-242f-4725-a11f-ee0e6fd6f6f1)

**Comment by janpio** [comment]
Prisma does not provide issue for `openssl-3.1.x`, these should be covered by `openssl-3.0.x`.

**Comment by CompeyDev** [comment]
Aha, that seems to fix it! Closing.

**Comment by steebchen** [comment]
Perfect, thanks for letting me know. I have to do some more testing before releasing, feel free to stay on that version for now

**Comment by steebchen** [comment]
This is fixed and release soon, however added a follow-up issue via #887 for people who want to use dynamically linked OpenSSL
