### ISSUE TITLE
Make alpine linux work

### ISSUE THREAD

**Issue by steebchen** [steebchen/prisma-client-go#886]
- [x] musl Prisma CLI binaries (#888)
- [x] ensure engine binaries work
- [x] test if setting musl query engine targets work (will be done via #887

**Comment by janpio** [comment]
Alpine doesn't like that static ones?

**Comment by steebchen** [comment]
Actually it does, it's just the Prisma CLI binary built with pkg

**Comment by steebchen** [comment]
Found a fix for the Prisma CLI binaries, pkg also allows building static binaries 😁 just needs some other fixes around the binary stuff
