### ISSUE TITLE
Generate seems to have problems when being used within a subdirectory of a JS monorepo

### ISSUE THREAD

**Issue by osilkin98** [steebchen/prisma-client-go#890]
I'm trying to write a serverless function with the Go prisma client to avoid some TypeScript-related issues with my larger monorepo. When trying to generate the client, it seems like Prisma still wants to use the client located in `node_modules` of the root monorepo. 

I have a feeling that this is 90% to do with how my project is configured and being used, I don't expect that most people would use the client this way. It still seems like unexpected behavior so I wanted to report it anyway.

When running `go run github.com/steebchen/prisma-client-go generate` in my newly instantiated Go repo:
```
╰─$ go run github.com/steebchen/prisma-client-go generate 
Environment variables loaded from ../../../../.env
Prisma schema loaded from schema.prisma
Error: Generator "/Users/oleg/Programming/case0/node_modules/@prisma/client/generator-build/index.js" failed:

node:internal/modules/cjs/loader:936
  throw err;
  ^
Error: Cannot find module '/Users/oleg/Programming/case0/functions/packages/plicanta/go-credit-refresh/--max-old-space-size=8096'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1951:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.runMain (pkg/prelude/bootstrap.js:1979:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

panic: could not run [generate]: exit status 1

goroutine 1 [running]:
main.main()
        /Users/oleg/.gvm/pkgsets/go1.18/global/pkg/mod/github.com/steebchen/prisma-client-go@v0.18.0/main.go:29 +0x34c
exit status 2
```

**Comment by steebchen** [comment]
You can't run the JS generator with the Go client at this time unfortunately. To generate the JS client you should use a NodeJS project and run `npx prisma generate`. See #877 and #455

**Comment by osilkin98** [comment]
@steebchen Oh, that makes sense. I was just copy-pasting my Prisma schema without modifying it at all. After reading your comment as well as the docs, I was able to get it to generate by setting 
```prisma
generator client {
  provider = "go run github.com/steebchen/prisma-client-go"
}
```
And then running `npx prisma generate`.

Thanks!
