### ISSUE TITLE
Feature request: embed migration SQL files into go binary and run migrations on startup

### ISSUE THREAD

**Issue by dahchon** [steebchen/prisma-client-go#952]

**Comment by steebchen** [comment]
Not sure if this is a good idea, as it would bloat the binary with something you would not need. Plus, in containerized environment, you would try to keep the startup time as low as possible I'd say, so running the migrations before a new deployment is probably best. 

Is there any reason why running migrate with go run does not work for you or where you see disadvantages?

**Comment by steebchen** [comment]
I created this more specific issue, which once implemented would then allow you to do migrations on startup by yourself. https://github.com/steebchen/prisma-client-go/issues/1134
