### ISSUE TITLE
The table `main.Currency` does not exist in the current database.

### ISSUE THREAD

**Issue by listepo** [steebchen/prisma-client-go#969]
```Unknown error occurred during request execution: "UNKNOWN: pql error: Error occurred during query execution: ConnectorError(ConnectorError { user_facing_error: Some(KnownError { message: "The table `main.Currency` does not exist in the current database.", meta: Object {"table": String("main.Currency")}, error_code: "P2021" }), kind: TableDoesNotExist { table: "main.Currency" }, transient: false })"```

I got this error, but a table Currency exists 
<img width="318" alt="Screenshot 2023-09-03 at 16 44 29" src="https://github.com/steebchen/prisma-client-go/assets/2510800/1c2e0acf-299c-40fa-b5dd-b4b65f772941">

My prisma
```
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator db {
  provider = "go run github.com/steebchen/prisma-client-go"
}

model Currency {
  id     String @id @default(cuid())
  title  String
  symbol String
  code   String
}

```

please tell me what i am doing wrong

**Comment by steebchen** [comment]
Did you run `db push` to sync your schema to your database?

```
go run github.com/steebchen/prisma-client-go db push
```


For production, please use the migrate command instead of db push (https://www.prisma.io/docs/concepts/components/prisma-migrate).

**Comment by listepo** [comment]
Yes, I run `go run github.com/steebchen/prisma-client-go db push` and `prisma migrate`
my DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres?schema=public
I didn't specify the `main` scheme
It seems that this is the default value on the client side

**Comment by steebchen** [comment]
I can't reproduce. Can you please share more info about your setup?

**Comment by steebchen** [comment]
Please re-open if this is still an issue for you.
