### ISSUE TITLE
Postgres arrays cannot be unmarshaled in raw queries

### ISSUE THREAD

**Issue by ImmaculatePine** [steebchen/prisma-client-go#981]
Hi,

There seem to be a problem with unmarshaling Postgres arrays when using raw queries.

The simplest code to reproduce that:

```go
var res []db.RawUserModel
if err := client.Prisma.QueryRaw(`
	SELECT * FROM "users"
`).Exec(ctx, &res); err != nil {
	log.Fatal(err)
}
```

It fails with `cannot unmarshal object into Go struct field RawUserModel.items of type raw.String` error. Queries done via regular `client.User.FindMany()` call work just fine.

### Schema

```sql
CREATE TABLE "users" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "items" TEXT[],

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);
```

### Reproduction

There is a tiny repo if you want to reproduce that https://github.com/ImmaculatePine/prisma-client-go-postgres-arrays

**Comment by steebchen** [comment]
Thanks for the issue and reproduction, will look into it soon

**Comment by steebchen** [comment]
This is now available in the main branch, you can try it out by running `go get github.com/prisma/prisma-client-go@main`. It's not yet released, but I'll cut a new one soon!

**Comment by ImmaculatePine** [comment]
Wow, thank you for such a quick fix ❤️ I updated the reproduction repo, it works as expected now 🎉
